/* automatically generated by rust-bindgen */

use core::CvArr;

pub type Enum_Unnamed1 = ::libc::c_uint;
pub const CV_INPAINT_NS: ::libc::c_uint = 0;
pub const CV_INPAINT_TELEA: ::libc::c_uint = 1;

extern "C" {
    pub fn cvInpaint(src: *const CvArr, inpaint_mask: *const CvArr,
                     dst: *mut CvArr, inpaintRange: ::libc::c_double,
                     flags: ::libc::c_int) -> ();
}
